on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: action/checkout@v4
        with:
          submodules: 'true'

      - name: hugo installation
        run:
          sudo apt-get update
          && sudo apt-get install -y hugo
          && sudo hugo
     
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public